version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - chroma
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECRET_KEY=replace-this-in-prod
      - DATABASE_URL=sqlite:///db.sqlite3
      - POSTGRES_USER=my_pg_user
      - POSTGRES_PASSWORD=my_pg_password
    
  chroma:
    build:
      context: ./backend/core/chroma
    volumes:
      - ./backend/core/chroma:/app
      - ./backend/playground:/app/playground
    ports:
      - "9000:9000"
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
      args:
        REACT_APP_API_URL: http://localhost:8000
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_pg_user
      POSTGRES_PASSWORD: my_pg_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: my_mysql_user
      MYSQL_PASSWORD: my_mysql_password
      MYSQL_ROOT_PASSWORD: my_mysql_root_password
    volumes:
      - ./mysql_data:/var/lib/mysql

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: my_mongo_password
    volumes:
      - ./mongo_data:/data/db
