version: '3.9'

services:

  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  frontend-37:
    build: ./frontend-37
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-37:/app
      - /app/node_modules
    environment:
      VITE_PROD: ${PROD}

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/data/db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: build
  #     args:
  #       REACT_APP_API_URL: http://localhost:8000
  #   ports:
  #     - "3000:3000"

  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

