# Generated by Django 5.2.1 on 2025-06-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='classrooms',
            field=models.ManyToManyField(related_name='courses', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(),
        ),
    ]
