name: Lint and test backend

on:
  push:
    branches: [main, pre-chroma]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/core 
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 isort
      
      - name: Run isort
        run: isort .
        
      - name: Run flake8
        run: flake8 .
        
      - name: Run tests
        run: cd .. && ./scripts/run_unit_tests.sh
